RIA-5679-Resolving-Vulnarabilities-For-case-api
hmcts/ia-case-api pull request #1047
Opened 2022-05-26 11:18 UTC by indu2019

https://tools.hmcts.net/jira/browse/RIA-5679, This 

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-5679

### Change description ###
https://tools.hmcts.net/jira/browse/RIA-5679

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-06-30 09:02 UTC, gregorio-massara submitted a review, later dismissed

2022-08-19 09:44 UTC, gregorio-massara requested changes
LG, but pls address new vulnerability
https://nvd.nist.gov/vuln/detail/CVE-2022-31197

Task :dependencyCheckAnalyze fail

2022-08-24 10:32 UTC, sajjadh-v1 approved these changes
Looks Good!

2022-08-24 10:33 UTC, gregorio-massara approved these changes

2022-08-24 12:41 UTC, merged