RIA-6183: Revoke Appellant's Access when LR completes NoC process
hmcts/ia-case-api pull request #1120
Opened 2022-10-10 16:05 UTC by augustio

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-6183

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-10-13 11:45 UTC, sajjadh-v1 requested changes

2022-10-13 11:45 UTC, sajjadh-v1 commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/ChangeRepresentationConfirmation.java
> +        logger.info("Found {} Citizen roles in the appeal with case ID {}", roleAssignmentResource.getRoleAssignmentResponse().size(), caseId);
Perhaps can be replaced with an exception as this needs attention

2022-10-17 15:32 UTC, markbrooks725 submitted a review, later dismissed

2022-10-17 15:38 UTC, sajjadh-v1 commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/service/RoleAssignmentService.java
> +                idamService.getUserToken(),
Is this current LR or the System user?

2022-10-18 08:18 UTC, markbrooks725 approved these changes

2022-10-18 08:18 UTC, merged