Ria 6490 non detained aaa
hmcts/ia-case-api pull request #1201
Opened 2022-12-12 15:17 UTC by JamieHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-6490

### Change description ###
Changed the screen order for a case-officer/judge in the editafterappealsubmitted event to the following:

Decision letter details
Upload the Notice of Decision (If changed, then as is in case creation flow)
Basic details
Tell us about your client's nationality (If changed, then as is in case creation flow)
Your clients address (If changed, then as is in case creation flow)
        **New code states that this page will not appear if the appellant in in detention**
The appellant's contact preference (If changed, then as is in case creation flow)
        **New code states that this page will not appear if the appellant in in detention**
Litigation friend (If changed, then as is in case creation flow)
Other appeals (If changed, then as is in case creation flow)
Fee remissions (If changed, then as is in case creation flow)
How to pay (If client is not eligible for fee remission)-
Check your answer
Success page

Changes made are for a case that is age assessment and is not detained.
ageAssessment="Yes" AND appellantInDetention!="Yes"

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-12-13 15:33 UTC, Ryan-Nesbitt commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/EditAppealAfterSubmitHandler.java
> +                Optional<String> mayBeDecisionLatter = asylumCase.read(DATE_ON_DECISION_LETTER, String.class);
typo on 'maybeDecisionLetter' variable

2022-12-13 15:34 UTC, Ryan-Nesbitt commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/NonDetainedAaaHandler.java
> +        //Optional<YesOrNo> ageAssessment = asylumCase.read(AGE_ASSESSMENT, YesOrNo.class);
Are these commented out lines still needed or can they be removed?

2022-12-13 15:35 UTC, Ryan-Nesbitt requested changes
Left some comments

2023-01-12 15:22 UTC, neha-aggarw requested changes
Still needs a handler to wipe the details of LitigationFriend, if hasLitigationFriend is set to No. Thomas is working on it as part of RIA-6433. After that goes in, some changes will be required by this work as well.

2023-02-02 10:24 UTC, closed without merging