RIA-6433 Added handlers to remove age assessment data if different pa…
hmcts/ia-case-api pull request #1225
Opened 2023-01-12 17:46 UTC by ThomasKKC

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-6433

### Change description ###
Added handlers to remove age assessment data if different path is chosen (non AAA)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-01-13 14:38 UTC, neha-aggarw requested changes
Small typo error.

2023-01-13 14:38 UTC, neha-aggarw commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AgeAssessmentDataEditAppealHandler.java
> +                log.info("Clearing Prison details for an IRC Detention centre.");
Typo on log message.

2023-01-16 09:46 UTC, neha-aggarw requested changes

2023-01-16 09:46 UTC, neha-aggarw commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AgeAssessmentDataEditAppealHandler.java
> +        asylumCase.clear(LITIGATION_FRIEND_PHONE_NUMBER);
You need to clear the field - litigationFriend

2023-01-16 09:53 UTC, neha-aggarw submitted a review, later dismissed
Do not merge till 6421.

2023-01-16 11:24 UTC, neha-aggarw approved these changes
DO NOT MERGE till RIA-6421.

2023-01-16 11:29 UTC, hussain-faruk approved these changes

2023-01-16 11:29 UTC, merged