Ria 6593 due date for ada
hmcts/ia-case-api pull request #1261
Opened 2023-02-08 10:31 UTC by JamieHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-6593

### Change description ###
For ADA cases once Request Case building event is completed, a standard direction will be sent to LR to build the case within 9 working days.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-02-08 15:16 UTC, neha-aggarw requested changes
Also, please add functional test for this change.

2023-02-08 15:16 UTC, neha-aggarw commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestCaseBuildingPreparer.java
> +            @Value("${legalRepresentativeBuildCase.dueInDaysAda}") int legalRepresentativeBuildCaseDueInDaysAda,
Following the existing naming convention: legalRepresentativeBuildCaseAda.dueInDays would be better here. Second object is to determine the event in specific. But only if you are putting another commit, add this change.

2023-02-09 15:10 UTC, neha-aggarw commented on src/functionalTest/resources/scenarios/RIA-6593-request-case-building.json
> +  "description": "RIA-6593 Request case building direction to legal representative",
This functional test is testing whether the notification is sent out on the completion of event : requestCaseBuilding and not if the due date is appropriate for ADA case. Please have a look at : RIA-892-RIA-2694-request-respondent-evidence-start.json.

2023-02-13 16:27 UTC, neha-aggarw submitted a review, later dismissed

2023-02-14 12:38 UTC, neha-aggarw approved these changes

2023-02-14 13:26 UTC, colmlynch60 approved these changes
LGTM

2023-02-14 13:26 UTC, merged