RIA-7246 capture phone number for legal representative
hmcts/ia-case-api pull request #1470
Opened 2023-06-30 10:07 UTC by DennisHoV1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-7246

### Change description ###
-Updated the LegalRepresentativeUpdateDetailsHandler, LegalRepresentativeUpdateDetailsPreparer and LegalRepresentativeDetailsHandler for handling the LR mobile number
-Added the new field of LR mobile number
-Added necessary unit test for related class

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-07-03 15:57 UTC, Marcellofabbri commented
@rajeshthuraiyur Would it be better to use the definition type PhoneUK instead of Text for the legalRep phone number?

FYI @DennisHoV1

2023-07-03 15:58 UTC, Marcellofabbri requested changes
@rajeshthuraiyur Would it be better to use the definition type PhoneUK instead of Text for the legalRep phone number?

FYI @DennisHoV1

2023-07-05 08:01 UTC, Marcellofabbri approved these changes

2023-07-06 14:51 UTC, rajeshthuraiyur approved these changes
LGTM

2023-07-06 15:02 UTC, merged