RIA-7908 change_party_to_appelant
hmcts/ia-case-api pull request #1668
Opened 2023-09-26 15:20 UTC by ikirsanov

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-7908

### Change description ###
Changed the party to Appellant conditions in standard directions for Internal case events:

- (Request case building - both ADA and non ADA)
-  (Review Home Office response - Non ADA only)
- (Request hearing requirement - Non ADA only)
- Added new junit tests and edited existed

### Checklist

- [ x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-09-27 12:12 UTC, neha-aggarw requested changes
The description of Fts should mention if the scenario is of Internal appeal (along with detention information).

2023-09-27 12:12 UTC, neha-aggarw commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestHearingRequirementsDirectionHandler.java
> +        if (HandlerUtils.isAipJourney(asylumCase) || isInternalCase(asylumCase) && isAppellantInDetention(asylumCase) && !isAcceleratedDetainedAppeal(asylumCase)) {
(HandlerUtils.isAipJourney(asylumCase) || 
(isInternalCase(asylumCase) && isAppellantInDetention(asylumCase) && !isAcceleratedDetainedAppeal(asylumCase))) 
Can we please change the condition.

2023-09-27 12:12 UTC, neha-aggarw commented on src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestHearingRequirementsDirectionTest.java
> +    void should_append_new_direction_to_existing_directions_for_the_case(YesOrNo yesOrNo, YesOrNo ada, JourneyType journeyType, Parties party) {
Please rename args to be more meaningful - like YesOrNo isAppellantInDetention

2023-09-27 12:12 UTC, neha-aggarw commented on src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/RequestResponseReviewHandlerTest.java
> +    void should_prepare_send_direction_fields(YesOrNo yesOrNo, YesOrNo ada, Parties expectedParties) {
same as above.

2023-09-27 12:12 UTC, neha-aggarw commented on src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/service/DirectionPartiesResolverTest.java
> +    void should_return_parties_for_send_direction_events(YesOrNo yesOrNo, Parties parties) {
same as above.

2023-09-27 16:11 UTC, colmlynch60 approved these changes
LGTM

2023-09-28 10:29 UTC, neha-aggarw approved these changes

2023-09-28 10:41 UTC, merged