Ria 7444 ejp part 2 start appeal
hmcts/ia-case-api pull request #1736
Opened 2023-10-24 08:50 UTC by Ryan-Nesbitt

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/RIA-7444

### Change description ###

- isNabaEnabledOOC field created to ensure this flag is visible between both EJP flow and other flows (when location screen is visible)
- isEjp handler created to set this field once the case is saved
- Unit and functional tests added

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-10-26 15:18 UTC, neha-aggarw requested changes

2023-10-26 15:18 UTC, neha-aggarw commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
> +        } else if (!sourceOfAppealEjp(asylumCase)) {
Lets have if (!sourceOfAppealEjp(asylumCase)) inside else.
else{
if (!sourceOfAppealEjp(asylumCase)) 
throw ......

2023-10-26 15:53 UTC, ThomasKKC approved these changes

2023-10-26 16:29 UTC, Ryan-Nesbitt commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AppealOutOfCountryEditAppealHandler.java
> +        } else if (!sourceOfAppealEjp(asylumCase)) {
Code refactored as suggested, Thanks

2023-10-27 08:21 UTC, colmlynch60 approved these changes
LGTM

2023-10-27 08:21 UTC, merged