RIA-8104 Add new ftpaDecisionRemadeRule32TextArea field and show conditions
hmcts/ia-case-api pull request #1953
Opened 2024-02-08 11:00 UTC by MiguelMartinRojas

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-8104

### Change description ###
RIA-8104 Add new ftpaDecisionRemadeRule32TextArea field and show conditions

2024-02-08 12:39 UTC, javierhmcts submitted a review, later dismissed
LGTM

2024-02-08 12:59 UTC, ThomasKKC requested changes
Need some functional tests for 31 and 32 scenarios. Maybe also the confirmation outcomes too.

2024-02-08 14:36 UTC, ThomasKKC approved these changes

2024-02-09 08:59 UTC, ikirsanov approved these changes

2024-02-09 09:03 UTC, merged