RIA-8157 update tribunal decision
hmcts/ia-case-api pull request #1980
Opened 2024-02-22 16:54 UTC by jamieclarkeHMCTS

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-8157

Change description
Update Tribunal decision - Event and screens for correct decision under R31

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-02-27 09:36 UTC, ThomasKKC requested changes

2024-02-27 09:36 UTC, ThomasKKC commented on src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionRule31MidEventTest.java
> +class UpdateTribunalDecisionRule31MidEventTest {
Need to finish the tests for this class

2024-02-27 09:36 UTC, ThomasKKC commented on src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionErrorRule31MidEventTest.java
> +class UpdateTribunalDecisionErrorRule31MidEventTest {
Can you add the "Cannot handle callback" tests here, see the class below.

2024-02-27 09:36 UTC, ThomasKKC commented on src/main/resources/application.yaml
> +decisionAndReasonsAmendedPdf.fileName: "Decision-and-reasons"
Is this used anywhere? We can remove it.

2024-02-27 09:36 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/UpdateTribunalDecisionConfirmation.java
> +        postSubmitResponse.setConfirmationBody(
Please add confirmation functional test.

2024-02-27 09:36 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionErrorRule31MidEvent.java
> +public class UpdateTribunalDecisionErrorRule31MidEvent implements PreSubmitCallbackHandler<AsylumCase> {
Can we rename this class? I know previously it was for error only, but we have merged the document name update with this class.

2024-02-27 09:36 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionErrorRule31MidEvent.java
> +        if (isDecisionAndReasonDocumentBeingUpdated == YES) {
Can we use .equals(YES) here? YesOrNO id is a String

2024-02-27 09:36 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionErrorRule31MidEvent.java
> +        } else if (isDecisionAndReasonDocumentBeingUpdated == NO &&
Same here, can we use .equals(No)?

2024-02-27 09:36 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionErrorRule31MidEvent.java
> +                response.addError("Amended Decision And Reasons Document must be present");
Do we need this? It is not part of the ticket criteria, the "MANDATORY" on CCD def will catch this

2024-02-27 09:36 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionErrorRule31MidEvent.java
> +            "No".equals(optionalTypesOfUpdateTribunalDecision.get().getValue().getLabel())) {
For visibility, can we flip the equals on this?
(optionalTypesOfUpdateTribunalDecision.get().getValue().getLabel()..equals("No")

2024-02-27 09:36 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionErrorRule31MidEvent.java
> +            response.addError("You must update the decision or the Decision and Reasons document to continue");
You might need to add full stop here, the prototype show it, can check with Elli

2024-02-27 09:47 UTC, ikirsanov commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionRule31MidEvent.java
> +            .map(type -> type == ALLOWED).orElse(false);
equals (as above Thomas mentioned)

2024-02-27 15:41 UTC, ikirsanov approved these changes

2024-02-27 15:44 UTC, ThomasKKC submitted a review, later dismissed

2024-02-27 16:44 UTC, ThomasKKC approved these changes

2024-02-27 19:41 UTC, DennisHoV1 approved these changes

2024-02-28 07:57 UTC, MiguelMartinRojas approved these changes

2024-02-28 08:54 UTC, merged