RIA-8157 Update tribunal decision fix
hmcts/ia-case-api pull request #2007
Opened 2024-03-06 17:03 UTC by jamieclarkeHMCTS

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-8157

### Change description ###
Fixes for issues relating to the event

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change

2024-03-07 09:00 UTC, ikirsanov approved these changes

2024-03-07 09:17 UTC, ThomasKKC requested changes
Need to update functional tests

2024-03-07 09:17 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionRule31MidEvent.java
> +        if (asylumCase.read(UPDATED_APPEAL_DECISION, String.class).isPresent()) {
We don't need to separate isDecisionAllowed and asylumCase.read(UPDATED_APPEAL_DECISION, String.class).isPresent(). They do the same thing.
Also need unit test to cover this part.

2024-03-07 09:17 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalAppealDecisionRule31.java
> +            if (isDecisionAndReasonDocumentBeingUpdated.equals(NO)) {
Unit test need to cover this 58-62

2024-03-07 17:46 UTC, ikirsanov submitted a review, later dismissed

2024-03-08 10:04 UTC, ikirsanov approved these changes

2024-03-08 10:16 UTC, merged