RIA-8210 update tribunal decision docuement tab
hmcts/ia-case-api pull request #2032
Opened 2024-03-14 23:19 UTC by jamieclarkeHMCTS

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-8210

### Change description ###
Update tribunal decision Rule31- Documents tab post event

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-03-15 09:57 UTC, ThomasKKC requested changes
Can you please update existing updateTribunalDecision rule32 functional tests to include the finalDecisionAndReasonsDocuments being updated.

2024-03-15 09:57 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/UpdateTribunalDecisionHandler.java
> +                    new ArrayList<>(),
Append to a new list wouldn't that wipe out all the decisions and reasons document? (cover letters, original decision document, and AMENDED cover letter)

2024-03-15 09:57 UTC, ThomasKKC commented on src/main/resources/application.yaml
> +      - "applyForFTPAAppellant"
We don't need to give HomeOffice this applyForFTPAAppellant permission

2024-03-15 10:25 UTC, ikirsanov approved these changes

2024-03-19 11:45 UTC, ThomasKKC approved these changes

2024-03-19 11:46 UTC, ikirsanov approved these changes

2024-03-19 11:59 UTC, merged