RIA-8290 - Reheard appeal - event refactor
hmcts/ia-case-api pull request #2052
Opened 2024-03-26 11:44 UTC by jamieclarkeHMCTS

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-8290

### Change description ###
Reheard appeal - Reheard appeal - event refactor

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-03-26 14:55 UTC, neha-aggarw requested changes

2024-03-26 14:55 UTC, neha-aggarw commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/MarkAppealAsRemittedUploadDecisionHandler.java
> +            asylumCase.write(CASE_FLAG_SET_ASIDE_REHEARD_EXISTS, YES);
We don't need a check here, we can just set the case flag.

2024-03-26 16:29 UTC, ThomasKKC approved these changes

2024-03-27 09:05 UTC, colmlynch60 approved these changes
LGTM

2024-03-27 09:05 UTC, neha-aggarw approved these changes

2024-03-27 09:17 UTC, merged