RIA-8969 add_progress_migrated_case
hmcts/ia-case-api pull request #2231
Opened 2024-07-15 14:32 UTC by ikirsanov

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-8969

### Change description ###
Created new event for moving Migrated cases to desired state handler and junit tests.

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-07-15 15:13 UTC, ThomasKKC requested changes

2024-07-15 15:13 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/AriaCreateCaseHandler.java
> +            && (Event.ARIA_CREATE_CASE == callback.getEvent() || Event.START_APPEAL == callback.getEvent());
Also check if isAriaMigrated is Yes for START_APPEAL please.

2024-07-15 15:13 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/migratedcase/ProgressMigratedCaseHandler.java
> +public class ProgressMigratedCaseHandler implements PreSubmitCallbackHandler<AsylumCase> {
Can we add FT for this please

2024-07-15 15:13 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/State.java
>  public enum State {
Can we update unit tests for this class?

2024-07-15 15:13 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/ccd/Event.java
> +    PROGRESS_MIGRATED_CASE("progressMigratedCase"),
Do we not need to add this event for adminofficer in application.yaml?

2024-07-16 07:51 UTC, ThomasKKC approved these changes

2024-07-16 08:13 UTC, MiguelMartinRojas approved these changes

2024-07-16 08:14 UTC, merged