Ria 3306 hearing notification
hmcts/ia-case-api pull request #622
Opened 2020-10-16 07:13 UTC by jkumar-moj

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-3306

### Change description ###
changes to trigger HO notification on listing a case

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2020-10-19 11:21 UTC, Lee365 requested changes

2020-10-19 11:21 UTC, Lee365 commented on src/functionalTest/resources/scenarios/RIA-3306-home-office-notifications-for-case-listing.json
> +  "enabled": "{$featureFlag.isHomeOfficeIntegrationEnabled}",
Need to change to Launch Darkly feature

2020-10-20 13:47 UTC, Lee365 commented on src/functionalTest/resources/scenarios/RIA-3306-home-office-notifications-for-case-listing.json
> +  "enabled": "{$featureFlag.isHomeOfficeIntegrationEnabled}",
Added LD feature

2020-10-22 13:31 UTC, Lee365 approved these changes
LGTM

2020-11-02 11:42 UTC, Lee365 submitted a review, later dismissed
LGTM

2020-11-19 17:29 UTC, Srihari-Nakkala approved these changes
LGTM

2021-01-06 17:06 UTC, Lee365 approved these changes
LGTM

2021-01-06 17:23 UTC, merged