Ria 3601 notifications retry
hmcts/ia-case-api pull request #635
Opened 2020-10-26 16:56 UTC by jkumar-moj

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-3601

### Change description ###
 Notification failure confirmation message on errors

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2020-11-02 11:57 UTC, makowalski commented on src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/AdjournWithoutDateConfirmationTest.java
> +    //@Before
we can remove commented part

2020-11-02 12:21 UTC, makowalski approved these changes
LGTM

2020-11-27 16:53 UTC, Srihari-Nakkala submitted a review, later dismissed
LGTM

2021-01-08 16:05 UTC, Lee365 requested changes

2021-01-08 16:05 UTC, Lee365 commented on src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestRespondentReviewConfirmationTest.java
> +    public void should_return_notification_failed_confirmation() {
Remove this 'public' modifier

2021-01-08 16:18 UTC, jkumar-moj commented on src/test/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/postsubmit/RequestRespondentReviewConfirmationTest.java
> +    public void should_return_notification_failed_confirmation() {
Removed

2021-01-08 16:40 UTC, Lee365 approved these changes
LGTM

2021-01-11 12:33 UTC, merged