Ria 3314 decided notification
hmcts/ia-case-api pull request #654
Opened 2020-11-04 17:05 UTC by jkumar-moj

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-3314

### Change description ###
trigger Home Office decided notification and notification failure message

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2020-11-05 23:43 UTC, Lee365 requested changes

2020-11-05 23:43 UTC, Lee365 commented on src/functionalTest/resources/scenarios/RIA-3314-send-decision-reasons-failure-confirmation-adminofficer.json
> +  "description": "RIA-3314 Send decision and reasons HO notification failure confirmation - Admin Officer",
launchDarklyKey missing

2020-11-05 23:43 UTC, Lee365 commented on src/functionalTest/resources/scenarios/RIA-3314-send-decision-reasons-failure-confirmation-caseofficer.json
> +  "description": "RIA-3314 Send decision and reasons HO notification failure confirmation - Case Officer",
launchDarklyKey missing

2020-11-05 23:43 UTC, Lee365 commented on src/functionalTest/resources/scenarios/RIA-3314-send-decision-reasons-failure-confirmation-judge.json
> +  "description": "RIA-3314 Send decision and reasons HO notification failure confirmation - Judge",
launchDarklyKey missing

2020-11-05 23:43 UTC, Lee365 commented on src/functionalTest/resources/scenarios/RIA-3314-send-decision-reasons-success-confirmation-judge.json
> +  "description": "RIA-3314 Send decision and reasons success confirmation",
launchDarklyKey missing

2020-11-06 13:40 UTC, jkumar-moj commented on src/functionalTest/resources/scenarios/RIA-3314-send-decision-reasons-failure-confirmation-adminofficer.json
> +  "description": "RIA-3314 Send decision and reasons HO notification failure confirmation - Admin Officer",
Flag added

2020-11-06 13:40 UTC, jkumar-moj commented on src/functionalTest/resources/scenarios/RIA-3314-send-decision-reasons-failure-confirmation-judge.json
> +  "description": "RIA-3314 Send decision and reasons HO notification failure confirmation - Judge",
FLag added

2020-11-23 12:05 UTC, Srihari-Nakkala approved these changes
LGTM

2021-01-12 15:25 UTC, Lee365 approved these changes
LGTM

2021-01-12 16:06 UTC, merged