Ria 3799
hmcts/ia-case-api pull request #694
Opened 2020-12-03 12:00 UTC by mkayad

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RIA-3799

### Change description ###

Ria 3799

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X ] No
```

2020-12-04 11:20 UTC, tarun-palisetty approved these changes

2021-01-07 12:52 UTC, divisathyan requested changes
Please check comment

2021-01-07 12:52 UTC, divisathyan commented on src/main/resources/application.yaml
> +  isfeePaymentEnabled: ${IA_FEEPAYMENT_ENABLED:true}
You may want to keep this false, as it will merge to master

2021-01-11 16:52 UTC, Lee365 approved these changes
LGTM

2021-01-13 11:54 UTC, mkayad commented
jenkins failing with an exception

2021-01-14 11:59 UTC, mkayad commented
we looked at the reason why the PR is not green and Marcin concluded the test will be failing until we release notification change to AAT and said that  this is acceptable exception because of notifications-api dependency

2021-04-07 15:59 UTC, tarun-palisetty submitted a review, later dismissed

2021-04-08 08:09 UTC, jkumar-moj submitted a review, later dismissed

2021-04-08 11:13 UTC, divisathyan approved these changes

2021-04-09 09:26 UTC, jkumar-moj approved these changes

2021-04-09 09:28 UTC, merged