Ria 2110
hmcts/ia-case-api pull request #746
Opened 2021-01-19 17:53 UTC by mkayad

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RIA-2110

### Change description ###

see ticket

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X ] No
```

2021-01-21 17:13 UTC, Lee365 requested changes

2021-01-21 17:13 UTC, Lee365 commented on src/main/resources/application.yaml
> +  connectionTimeout: 5000
This file change needs to be reverted

2021-01-22 09:06 UTC, mkayad commented on src/main/resources/application.yaml
> +  connectionTimeout: 5000
changed to normal timeout times

2021-01-22 12:08 UTC, Lee365 approved these changes
LGTM

2021-01-28 15:45 UTC, Lee365 requested changes

2021-01-29 21:05 UTC, Lee365 approved these changes
LGTM

2021-01-29 23:59 UTC, Lee365 requested changes

2021-01-29 23:59 UTC, Lee365 commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/OutOfCountryDecisionType.java
> +    REFUSAL_OF_PROTECTION("refusalOfProtection", "A decision to refuse a human rights or protection claim, or deprive you of British citizenship, where you can only apply after your client has left t
ccd-def has this "refusalOfPA"
Either this has to be corrected or ccd-def

2021-02-04 18:52 UTC, Lee365 commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/entities/OutOfCountryDecisionType.java
> +    REFUSAL_OF_PROTECTION("refusalOfProtection", "A decision to refuse a human rights or protection claim, or deprive you of British citizenship, where you can only apply after your client has left t
ccd-def corrected

2021-02-04 18:53 UTC, Lee365 commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseNotificationsHandler.java
> +            value -> value.equals(YesOrNo.YES)).orElse(false)) {
changed

2021-02-04 18:53 UTC, Lee365 commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/HomeOfficeCaseValidateHandler.java
> +            value -> value.equals(YesOrNo.YES)).orElse(false)) {
changed

2021-02-04 18:53 UTC, Srihari-Nakkala submitted a review, later dismissed
LGTM

2021-02-04 18:55 UTC, Lee365 submitted a review, later dismissed

2021-02-26 11:03 UTC, Lee365 approved these changes
LGTM

2021-02-26 11:20 UTC, merged