RIA-4722 initial commit
hmcts/ia-case-api pull request #984
Opened 2021-10-06 13:45 UTC by srinivasuluputcha

:

###https://tools.hmcts.net/jira/browse/RIA-4722 ###

### Clarifying question: Process to enable correct state to be set when clarifying questions is completed###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2021-10-13 08:25 UTC, jkumar-moj requested changes
@srinivasuluputcha good one. looks good couple of minor comments to ensure it is already covered and minor change in the functional test. Could you please take a look and confirm?

2021-10-13 08:25 UTC, jkumar-moj commented on src/main/java/uk/gov/hmcts/reform/iacaseapi/domain/handlers/presubmit/CompleteClarifyingQuestionsHandler.java
> +            .findFirst();
Is it ok to pick the first one? Will it always be sorted and has it been tested with multiple rounds of clarifying questions?

2021-10-18 13:51 UTC, srinivasuluputcha commented on src/functionalTest/resources/scenarios/RIA-4722-direction-request-clarifying-questions.json
> +        "preClarifyingState": "reasonsForAppealSubmitted"
I've fixed this one.

2021-10-18 13:59 UTC, jkumar-moj approved these changes
👍

2022-02-04 13:08 UTC, bradsorour approved these changes
LGTM

2022-02-04 14:52 UTC, merged